# ===============================
# Application & Server
# ===============================
spring.application.name=psu-java-sample-project
server.port=8080

# ===============================
# PostgreSQL Database (????????)
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/javaproject
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=java_user
spring.datasource.password=test123

# ===============================
# JPA / Hibernate (PostgreSQL)
# ===============================
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


spring.jpa.properties.hibernate.hbm2ddl.extra_physical_table_types=VIEW

# ===============================
# ????????? H2 ???????
# ===============================
# spring.h2.console.enabled=false  # ????? ???????? ??????????????????

# ===============================
# Thymeleaf
# ===============================
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

# ===============================
# Encoding
# ===============================
spring.http.encoding.charset=UTF-8
spring.http.encoding.enabled=true
spring.http.encoding.force=true

# ===============================
# Logging
# ===============================
logging.level.com.music.album=DEBUG
logging.level.org.springframework.web=INFO
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

logging.level.org.hibernate.tool.schema.internal=DEBUG